version: '1.0'
generated: '2025-11-03T23:10:09.808513'
dataset: ml_dataset_with_csz.parquet
total_features: 389
feature_hash: 34ab4367fb2ec33c
features:
  all:
  - Close
  - High
  - Low
  - Open
  - TurnoverValue
  - Volume
  - activity_ratio
  - activity_z
  - actual_ret_1d
  - adv_jpy
  - adx_14
  - alpha_1d
  - alpha_5d
  - alpha_vs_regime
  - alpha_vs_sec_1d
  - amihud_20
  - atr_14
  - bb_bw
  - bb_position
  - bb_width
  - beta_20d_raw
  - beta_60d
  - beta_60d_raw
  - beta_rolling
  - beta_stability_60d
  - breadth_pos
  - close_to_high
  - close_to_low
  - days_since_flow
  - dmi_application_date
  - dmi_credit_ratio
  - dmi_d_long_1d
  - dmi_d_long_to_adv1d
  - dmi_d_net_1d
  - dmi_d_net_to_adv1d
  - dmi_d_ratio_1d
  - dmi_d_short_1d
  - dmi_d_short_to_adv1d
  - dmi_days_since_app
  - dmi_days_since_pub
  - dmi_imbalance
  - dmi_impulse
  - dmi_long
  - dmi_long_to_adv20
  - dmi_neg_share_long
  - dmi_neg_share_short
  - dmi_net
  - dmi_publish_reason
  - dmi_published_date
  - dmi_reason_count
  - dmi_reason_dailypublication
  - dmi_reason_monitoring
  - dmi_reason_precautionbyjsf
  - dmi_reason_restricted
  - dmi_reason_restrictedbyjsf
  - dmi_reason_unclearorseconalert
  - dmi_short
  - dmi_short_long_ratio
  - dmi_short_to_adv20
  - dmi_std_share_long
  - dmi_std_share_short
  - dmi_total
  - dmi_total_to_adv20
  - dmi_tse_reg_level
  - dmi_z26_d_short_1d
  - dmi_z26_long
  - dmi_z26_short
  - dmi_z26_total
  - dollar_volume
  - ema_10
  - ema_20
  - ema_200
  - ema_5
  - ema_60
  - feat_ret_10d
  - feat_ret_1d
  - feat_ret_20d
  - feat_ret_5d
  - flag_extreme_ret
  - flag_freeze
  - flag_low_adv
  - flag_penny
  - flag_zero_vol
  - flow_activity_high
  - flow_activity_low
  - flow_activity_ratio
  - flow_activity_z
  - flow_breadth_pos
  - flow_days_since
  - flow_foreign_net_pos
  - flow_foreign_net_ratio
  - flow_foreign_net_z
  - flow_foreign_share
  - flow_impulse
  - flow_individual_net_ratio
  - flow_individual_net_z
  - flow_shock_flag
  - flow_smart_idx
  - flow_smart_mom4
  - flow_smart_pos
  - foreign_share_activity
  - foreigners_net_ratio
  - graph_avg_neigh_deg
  - graph_closeness
  - graph_clustering
  - graph_comp_id
  - graph_comp_size
  - graph_core
  - graph_degree
  - graph_degree_centrality
  - graph_degree_in_comp
  - graph_degree_z
  - graph_degree_z_in_comp
  - graph_isolated
  - graph_local_density
  - graph_pagerank
  - graph_pagerank_share_comp
  - graph_pagerank_z_in_comp
  - high_low_ratio
  - idio_vol_ratio
  - individuals_net_ratio
  - is_borrowable
  - is_ema10_valid
  - is_ema200_valid
  - is_ema20_valid
  - is_ema5_valid
  - is_flow_valid
  - is_halt_20201001
  - is_margin_valid
  - is_rsi2_valid
  - is_sec_cs_valid
  - is_section_fallback
  - is_stmt_valid
  - is_valid_ma
  - lag_returns_1d
  - log_returns_10d
  - log_returns_1d
  - log_returns_20d
  - log_returns_5d
  - long_z52
  - ma_gap_20_60
  - ma_gap_5_20
  - macd
  - macd_hist_slope
  - macd_histogram
  - macd_signal
  - macd_slope_in_sec_z
  - margin_credit_ratio
  - margin_d_long_to_adv20
  - margin_d_long_wow
  - margin_d_net_wow
  - margin_d_ratio_wow
  - margin_d_short_to_adv20
  - margin_d_short_wow
  - margin_days_since
  - margin_gross_mom4
  - margin_gross_z52
  - margin_imbalance
  - margin_impulse
  - margin_issue_type
  - margin_long_to_adv20
  - margin_long_tot
  - margin_neg_share_long
  - margin_neg_share_short
  - margin_net
  - margin_short_to_adv20
  - margin_short_tot
  - margin_std_share_long
  - margin_std_share_short
  - margin_total_gross
  - mkt_atr_14
  - mkt_bb_bw
  - mkt_bb_bw_z
  - mkt_bb_pct_b
  - mkt_big_move_flag
  - mkt_bull_200
  - mkt_bull_20d
  - mkt_dd_from_peak
  - mkt_dd_from_peak_z
  - mkt_dev_20
  - mkt_ema20_slope_3
  - mkt_ema_20
  - mkt_ema_200
  - mkt_ema_5
  - mkt_ema_60
  - mkt_gap_5_20
  - mkt_high_vol
  - mkt_high_vol_regime
  - mkt_natr_14
  - mkt_ret_10d
  - mkt_ret_1d
  - mkt_ret_1d_z
  - mkt_ret_20d
  - mkt_ret_5d
  - mkt_squeeze
  - mkt_trend_up
  - mkt_vol_20d
  - mkt_vol_20d_z
  - peer_corr_mean
  - peer_count
  - pk_vol_20
  - pk_vol_60
  - price_to_sma20
  - price_to_sma5
  - price_to_sma60
  - price_unchanged
  - quality_bad
  - rank_ret_prev_1d
  - ratio_z52
  - realized_volatility
  - rel_strength_5d
  - ret_prev_10d_in_sec_z
  - ret_prev_10d_vs_sec
  - ret_prev_1d_in_sec_z
  - ret_prev_1d_rank_in_sec
  - ret_prev_1d_vs_sec
  - ret_prev_5d_in_sec_z
  - ret_prev_5d_vs_sec
  - returns_10d
  - returns_120d
  - returns_1d
  - returns_20d
  - returns_5d
  - returns_60d
  - rs_vol_20
  - rs_vol_60
  - rsi14_in_sec_z
  - rsi_14
  - rsi_2
  - rsi_delta
  - rsi_vol_in_sec_z
  - rsi_vol_interact
  - rv20_in_sec_z
  - sec17_onehot_-1
  - sec17_onehot_0
  - sec17_onehot_1
  - sec17_onehot_10
  - sec17_onehot_11
  - sec17_onehot_12
  - sec17_onehot_13
  - sec17_onehot_14
  - sec17_onehot_15
  - sec17_onehot_16
  - sec17_onehot_17
  - sec17_onehot_2
  - sec17_onehot_3
  - sec17_onehot_4
  - sec17_onehot_5
  - sec17_onehot_6
  - sec17_onehot_7
  - sec17_onehot_8
  - sec17_onehot_9
  - sec17_onehot_other
  - sec33_daily_freq
  - sec_ema_20
  - sec_ema_5
  - sec_gap_5_20
  - sec_mom_20
  - sec_ret_1d_eq
  - sec_ret_1d_mcap
  - sec_ret_20d_eq
  - sec_ret_20d_mcap
  - sec_ret_5d_eq
  - sec_ret_5d_mcap
  - sec_small_flag
  - sec_vol_20
  - sec_vol_20_z
  - sector17_code
  - sector17_id
  - sector17_name
  - sector33_code
  - sector33_id
  - sector33_name
  - shares_outstanding
  - short_z52
  - sma_10
  - sma_120
  - sma_20
  - sma_5
  - sma_60
  - smart_money_idx
  - smart_money_mom4
  - ss_activity
  - ss_activity_z52
  - ss_balance
  - ss_balance_change
  - ss_balance_ratio
  - ss_cond_pressure
  - ss_extreme_flag
  - ss_extreme_high
  - ss_extreme_low
  - ss_mean_reversion_signal
  - ss_mkt_restrict_share
  - ss_mkt_short_breadth_q80
  - ss_mkt_short_share
  - ss_momentum_10d
  - ss_momentum_5d
  - ss_p05_252d
  - ss_p95_252d
  - ss_percentile_total
  - ss_ratio
  - ss_ratio_ma20
  - ss_ratio_ma5
  - ss_ratio_z52
  - ss_rel_restrict_share
  - ss_rel_short_share
  - ss_sec33_restrict_share
  - ss_sec33_restrict_share_d1
  - ss_sec33_short_accel
  - ss_sec33_short_mom5
  - ss_sec33_short_share
  - ss_sec33_short_share_d1
  - ss_sec33_short_share_z60
  - ss_sec33_short_turnover
  - ss_sec33_short_turnover_z252
  - ss_squeeze_setup
  - ss_trend_strength
  - ss_vol_20d
  - ss_vol_5d
  - ss_volume_abs
  - ss_volume_momentum_5d
  - ss_volume_ratio
  - ss_volume_ratio_z52
  - stmt_change_in_est
  - stmt_days_since_statement
  - stmt_imp_statement
  - stmt_nc_flag
  - stmt_npm
  - stmt_opm
  - stmt_profit_margin
  - stmt_progress_np
  - stmt_progress_op
  - stmt_rev_div_fore
  - stmt_rev_fore_eps
  - stmt_rev_fore_np
  - stmt_rev_fore_op
  - stmt_revenue_growth
  - stmt_roa
  - stmt_roe
  - stmt_yoy_np
  - stmt_yoy_op
  - stmt_yoy_sales
  - stoch_k
  - trend_align_mkt
  - turnover_rate
  - vcm_in_sec_z
  - vol_confirmed_mom
  - volatility_10d
  - volatility_20d
  - volatility_5d
  - volatility_60d
  - volume_accel
  - volume_in_sec_z
  - volume_ma_20
  - volume_ma_5
  - volume_rank_in_sec
  - volume_ratio_20
  - volume_ratio_5
  - vov_20
  - vov_60
  - x_alpha_meanrev_stable
  - x_bbneg_rvol5
  - x_bbpos_rvol5
  - x_bo_gate
  - x_breadth_rel
  - x_credit_rev_bias
  - x_dmi_impulse_dir
  - x_flow_smart_rel
  - x_foreign_relsec
  - x_liquidityshock_mom
  - x_mom_sh_10
  - x_mom_sh_5
  - x_mom_sh_5_mktneu
  - x_pead_effect
  - x_pead_times_mkt
  - x_rel_sec_mom
  - x_rev_gate
  - x_rvol5_bb
  - x_rvol5_dir
  - x_squeeze_pressure
  - x_trend_intensity
  - x_trend_intensity_g
  - x_tri_align
  - x_z_sec_gap_mom
  - yz_vol_20
  - yz_vol_60
  - z_close_20
  - z_in_sec_ma_gap_5_20
  - z_in_sec_returns_5d
  by_category:
    temporal:
    - Close
    - High
    - Low
    - Open
    - atr_14
    - bb_bw
    - bb_position
    - bb_width
    - lag_returns_1d
    - log_returns_10d
    - log_returns_1d
    - log_returns_20d
    - log_returns_5d
    - macd_hist_slope
    - macd_histogram
    - macd_signal
    - macd_slope_in_sec_z
    - mkt_atr_14
    - mkt_bb_bw
    - mkt_bb_bw_z
    - mkt_bb_pct_b
    - mkt_natr_14
    - returns_10d
    - returns_120d
    - returns_1d
    - returns_20d
    - returns_5d
    - returns_60d
    - rsi_14
    - rsi_2
    - rsi_delta
    - rsi_vol_in_sec_z
    - rsi_vol_interact
    - ss_momentum_10d
    - ss_momentum_5d
    - ss_volume_momentum_5d
    - volatility_10d
    - volatility_20d
    - volatility_5d
    - volatility_60d
    - z_in_sec_returns_5d
    flow:
    - adv_jpy
    - dollar_volume
    - flow_activity_high
    - flow_activity_low
    - flow_activity_ratio
    - flow_activity_z
    - flow_breadth_pos
    - flow_days_since
    - flow_foreign_net_pos
    - flow_foreign_net_ratio
    - flow_foreign_net_z
    - flow_foreign_share
    - flow_impulse
    - flow_individual_net_ratio
    - flow_individual_net_z
    - flow_shock_flag
    - flow_smart_idx
    - flow_smart_mom4
    - flow_smart_pos
    - is_flow_valid
    - ss_sec33_short_turnover
    - ss_sec33_short_turnover_z252
    - ss_volume_abs
    - ss_volume_ratio
    - ss_volume_ratio_z52
    - turnover_rate
    - volume_accel
    - volume_in_sec_z
    - volume_ma_20
    - volume_ma_5
    - volume_rank_in_sec
    - volume_ratio_20
    - volume_ratio_5
    - x_flow_smart_rel
    graph:
    - graph_avg_neigh_deg
    - graph_closeness
    - graph_clustering
    - graph_comp_id
    - graph_comp_size
    - graph_core
    - graph_degree
    - graph_degree_centrality
    - graph_degree_in_comp
    - graph_degree_z
    - graph_degree_z_in_comp
    - graph_isolated
    - graph_local_density
    - graph_pagerank
    - graph_pagerank_share_comp
    - graph_pagerank_z_in_comp
    - peer_corr_mean
    - peer_count
    fundamental:
    - stmt_profit_margin
    - stmt_roa
    - stmt_roe
    other:
    - TurnoverValue
    - Volume
    - activity_ratio
    - activity_z
    - actual_ret_1d
    - adx_14
    - alpha_1d
    - alpha_5d
    - alpha_vs_regime
    - alpha_vs_sec_1d
    - amihud_20
    - beta_20d_raw
    - beta_60d
    - beta_60d_raw
    - beta_rolling
    - beta_stability_60d
    - breadth_pos
    - close_to_high
    - close_to_low
    - days_since_flow
    - dmi_application_date
    - dmi_credit_ratio
    - dmi_d_long_1d
    - dmi_d_long_to_adv1d
    - dmi_d_net_1d
    - dmi_d_net_to_adv1d
    - dmi_d_ratio_1d
    - dmi_d_short_1d
    - dmi_d_short_to_adv1d
    - dmi_days_since_app
    - dmi_days_since_pub
    - dmi_imbalance
    - dmi_impulse
    - dmi_long
    - dmi_long_to_adv20
    - dmi_neg_share_long
    - dmi_neg_share_short
    - dmi_net
    - dmi_publish_reason
    - dmi_published_date
    - dmi_reason_count
    - dmi_reason_dailypublication
    - dmi_reason_monitoring
    - dmi_reason_precautionbyjsf
    - dmi_reason_restricted
    - dmi_reason_restrictedbyjsf
    - dmi_reason_unclearorseconalert
    - dmi_short
    - dmi_short_long_ratio
    - dmi_short_to_adv20
    - dmi_std_share_long
    - dmi_std_share_short
    - dmi_total
    - dmi_total_to_adv20
    - dmi_tse_reg_level
    - dmi_z26_d_short_1d
    - dmi_z26_long
    - dmi_z26_short
    - dmi_z26_total
    - ema_10
    - ema_20
    - ema_200
    - ema_5
    - ema_60
    - feat_ret_10d
    - feat_ret_1d
    - feat_ret_20d
    - feat_ret_5d
    - flag_extreme_ret
    - flag_freeze
    - flag_low_adv
    - flag_penny
    - flag_zero_vol
    - foreign_share_activity
    - foreigners_net_ratio
    - high_low_ratio
    - idio_vol_ratio
    - individuals_net_ratio
    - is_borrowable
    - is_ema10_valid
    - is_ema200_valid
    - is_ema20_valid
    - is_ema5_valid
    - is_halt_20201001
    - is_margin_valid
    - is_rsi2_valid
    - is_sec_cs_valid
    - is_section_fallback
    - is_stmt_valid
    - is_valid_ma
    - long_z52
    - ma_gap_20_60
    - ma_gap_5_20
    - macd
    - margin_credit_ratio
    - margin_d_long_to_adv20
    - margin_d_long_wow
    - margin_d_net_wow
    - margin_d_ratio_wow
    - margin_d_short_to_adv20
    - margin_d_short_wow
    - margin_days_since
    - margin_gross_mom4
    - margin_gross_z52
    - margin_imbalance
    - margin_impulse
    - margin_issue_type
    - margin_long_to_adv20
    - margin_long_tot
    - margin_neg_share_long
    - margin_neg_share_short
    - margin_net
    - margin_short_to_adv20
    - margin_short_tot
    - margin_std_share_long
    - margin_std_share_short
    - margin_total_gross
    - mkt_big_move_flag
    - mkt_bull_200
    - mkt_bull_20d
    - mkt_dd_from_peak
    - mkt_dd_from_peak_z
    - mkt_dev_20
    - mkt_ema20_slope_3
    - mkt_ema_20
    - mkt_ema_200
    - mkt_ema_5
    - mkt_ema_60
    - mkt_gap_5_20
    - mkt_high_vol
    - mkt_high_vol_regime
    - mkt_ret_10d
    - mkt_ret_1d
    - mkt_ret_1d_z
    - mkt_ret_20d
    - mkt_ret_5d
    - mkt_squeeze
    - mkt_trend_up
    - mkt_vol_20d
    - mkt_vol_20d_z
    - pk_vol_20
    - pk_vol_60
    - price_to_sma20
    - price_to_sma5
    - price_to_sma60
    - price_unchanged
    - quality_bad
    - rank_ret_prev_1d
    - ratio_z52
    - realized_volatility
    - rel_strength_5d
    - ret_prev_10d_in_sec_z
    - ret_prev_10d_vs_sec
    - ret_prev_1d_in_sec_z
    - ret_prev_1d_rank_in_sec
    - ret_prev_1d_vs_sec
    - ret_prev_5d_in_sec_z
    - ret_prev_5d_vs_sec
    - rs_vol_20
    - rs_vol_60
    - rsi14_in_sec_z
    - rv20_in_sec_z
    - sec17_onehot_-1
    - sec17_onehot_0
    - sec17_onehot_1
    - sec17_onehot_10
    - sec17_onehot_11
    - sec17_onehot_12
    - sec17_onehot_13
    - sec17_onehot_14
    - sec17_onehot_15
    - sec17_onehot_16
    - sec17_onehot_17
    - sec17_onehot_2
    - sec17_onehot_3
    - sec17_onehot_4
    - sec17_onehot_5
    - sec17_onehot_6
    - sec17_onehot_7
    - sec17_onehot_8
    - sec17_onehot_9
    - sec17_onehot_other
    - sec33_daily_freq
    - sec_ema_20
    - sec_ema_5
    - sec_gap_5_20
    - sec_mom_20
    - sec_ret_1d_eq
    - sec_ret_1d_mcap
    - sec_ret_20d_eq
    - sec_ret_20d_mcap
    - sec_ret_5d_eq
    - sec_ret_5d_mcap
    - sec_small_flag
    - sec_vol_20
    - sec_vol_20_z
    - sector17_code
    - sector17_id
    - sector17_name
    - sector33_code
    - sector33_id
    - sector33_name
    - shares_outstanding
    - short_z52
    - sma_10
    - sma_120
    - sma_20
    - sma_5
    - sma_60
    - smart_money_idx
    - smart_money_mom4
    - ss_activity
    - ss_activity_z52
    - ss_balance
    - ss_balance_change
    - ss_balance_ratio
    - ss_cond_pressure
    - ss_extreme_flag
    - ss_extreme_high
    - ss_extreme_low
    - ss_mean_reversion_signal
    - ss_mkt_restrict_share
    - ss_mkt_short_breadth_q80
    - ss_mkt_short_share
    - ss_p05_252d
    - ss_p95_252d
    - ss_percentile_total
    - ss_ratio
    - ss_ratio_ma20
    - ss_ratio_ma5
    - ss_ratio_z52
    - ss_rel_restrict_share
    - ss_rel_short_share
    - ss_sec33_restrict_share
    - ss_sec33_restrict_share_d1
    - ss_sec33_short_accel
    - ss_sec33_short_mom5
    - ss_sec33_short_share
    - ss_sec33_short_share_d1
    - ss_sec33_short_share_z60
    - ss_squeeze_setup
    - ss_trend_strength
    - ss_vol_20d
    - ss_vol_5d
    - stmt_change_in_est
    - stmt_days_since_statement
    - stmt_imp_statement
    - stmt_nc_flag
    - stmt_npm
    - stmt_opm
    - stmt_progress_np
    - stmt_progress_op
    - stmt_rev_div_fore
    - stmt_rev_fore_eps
    - stmt_rev_fore_np
    - stmt_rev_fore_op
    - stmt_revenue_growth
    - stmt_yoy_np
    - stmt_yoy_op
    - stmt_yoy_sales
    - stoch_k
    - trend_align_mkt
    - vcm_in_sec_z
    - vol_confirmed_mom
    - vov_20
    - vov_60
    - x_alpha_meanrev_stable
    - x_bbneg_rvol5
    - x_bbpos_rvol5
    - x_bo_gate
    - x_breadth_rel
    - x_credit_rev_bias
    - x_dmi_impulse_dir
    - x_foreign_relsec
    - x_liquidityshock_mom
    - x_mom_sh_10
    - x_mom_sh_5
    - x_mom_sh_5_mktneu
    - x_pead_effect
    - x_pead_times_mkt
    - x_rel_sec_mom
    - x_rev_gate
    - x_rvol5_bb
    - x_rvol5_dir
    - x_squeeze_pressure
    - x_trend_intensity
    - x_trend_intensity_g
    - x_tri_align
    - x_z_sec_gap_mom
    - yz_vol_20
    - yz_vol_60
    - z_close_20
    - z_in_sec_ma_gap_5_20
metadata_columns:
- Code
- Date
- LocalCode
- MarketCode
- Section
- row_idx
- section_norm
target_columns:
- target_10d
- target_10d_binary
- target_1d
- target_1d_binary
- target_20d
- target_20d_binary
- target_5d
- target_5d_binary
cs_z_columns:
- Close_cs_z
- High_cs_z
- Low_cs_z
- Open_cs_z
- atr_14_cs_z
- bb_bw_cs_z
- bb_position_cs_z
- bb_width_cs_z
- dollar_volume_cs_z
- flow_activity_ratio_cs_z
- flow_activity_z_cs_z
- flow_breadth_pos_cs_z
- flow_days_since_cs_z
- flow_foreign_net_ratio_cs_z
- flow_foreign_net_z_cs_z
- flow_foreign_share_cs_z
- flow_individual_net_ratio_cs_z
- flow_individual_net_z_cs_z
- flow_smart_idx_cs_z
- flow_smart_mom4_cs_z
- macd_hist_slope_cs_z
- macd_histogram_cs_z
- macd_signal_cs_z
- macd_slope_in_sec_z_cs_z
- peer_corr_mean_cs_z
- peer_count_cs_z
- realized_volatility_cs_z
- returns_10d_cs_z
- returns_120d_cs_z
- returns_1d_cs_z
- returns_20d_cs_z
- returns_5d_cs_z
- returns_60d_cs_z
- rsi_14_cs_z
- rsi_2_cs_z
- rsi_delta_cs_z
- rsi_vol_in_sec_z_cs_z
- rsi_vol_interact_cs_z
- turnover_rate_cs_z
- volatility_10d_cs_z
- volatility_20d_cs_z
- volatility_5d_cs_z
- volatility_60d_cs_z
- volume_accel_cs_z
- volume_in_sec_z_cs_z
- volume_ma_20_cs_z
- volume_ma_5_cs_z
- volume_rank_in_sec_cs_z
- volume_ratio_20_cs_z
- volume_ratio_5_cs_z
statistics:
  total_columns: 454
  metadata: 7
  targets: 8
  features: 389
  cs_z_features: 50
